### ISSUE TITLE
Batch Conversion

### ISSUE THREAD

**Issue by danbam123** [PetrVys/MotionPhoto2#3]
Hi, first off thank you for creating this project! I ran it locally and it works great and just as expected.  

Currently it seems like I have to run this command for every single file manually.  Are there plans to include batch support? Ideally running this program can match all files in the same directory for example.  The https://github.com/mihir-io/MotionPhotoMuxer project allows you to pass in a --dir flag

**Comment by tannerkrewson** [comment]
there is a fork here that seems to add batch processing with a python script https://github.com/bs10081/LivePhotos-2-GoogleMotion

**Comment by danbam123** [comment]
Thanks! Looks promising. Will check it out.

**Comment by PetrVys** [comment]
Good idea... I gave up on the project a bit because of Issue #2 (HDR is more important to me than Live Photos), but I've added support for processing directories into the runner batch. I do not want to add dependencies on other runtimes, powershell and batch does not need any runtime installed :-)
